// Build a single-file browser bundle at dist/browser.js.
// Same no-transpiler approach as build-cjs.js: the src/ modules use a small,
// predictable subset of import/export syntax, so we concatenate the files in
// dependency order, strip the module syntax, and re-export the public API.
// The guarded `await import('node:fs')` shims in events.js/splits.js stay
// intact — they resolve only in Node and fall back quietly in the browser.

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '..');
const srcDir = join(root, 'src');
const outDir = join(root, 'dist');

// Dependency order — a file may only reference names from files before it
// (function declarations are hoisted anyway, but this keeps output readable).
const ORDER = [
  'prng.js',
  'symbols.js',
  'numeric.js',
  'interval.js',
  'generator.js',
  'events.js',
  'splits.js',
  'svg.js',
  'html.js'
];

function stripModuleSyntax(source) {
  let s = source;
  // Single-line static imports (all imports in src/ are single-line)
  s = s.replace(/^import\s[^;]*;?\s*$/gm, '');
  // `export function`/`export async function`/`export const` -> drop `export `
  s = s.replace(/^export\s+(?=((async\s+)?function|const|let|var|class)\b)/gm, '');
  // `export { a, b }` / `export { a, b } from './x.js'` (possibly multi-line)
  s = s.replace(/^export\s*\{[^}]*\}\s*(from\s*['"][^'"]+['"])?\s*;?/gm, '');
  return s;
}

// Public API names come from index.js's `export { ... } from` clauses.
function publicApiNames() {
  const indexSrc = readFileSync(join(srcDir, 'index.js'), 'utf8');
  const names = [];
  for (const m of indexSrc.matchAll(/^export\s*\{([^}]+)\}\s*from\s*['"][^'"]+['"]\s*;?/gm)) {
    for (const part of m[1].split(',')) {
      const name = part.trim();
      if (name) names.push(name);
    }
  }
  return names;
}

// Guard against duplicate top-level declarations — a silent collision would
// only surface as a SyntaxError for end users of the bundle.
function assertNoDuplicateDeclarations(bundle) {
  const seen = new Map();
  for (const m of bundle.matchAll(/^(?:async\s+)?function\s+(\w+)|^(?:const|let|var)\s+(\w+)/gm)) {
    const name = m[1] || m[2];
    if (seen.has(name)) {
      throw new Error(`build-browser: duplicate top-level declaration "${name}"`);
    }
    seen.set(name, true);
  }
}

mkdirSync(outDir, { recursive: true });

let bundle =
  '// stock-market-gen — single-file browser build.\n' +
  '// Generated by scripts/build-browser.js — do not edit.\n\n';

for (const file of ORDER) {
  const source = readFileSync(join(srcDir, file), 'utf8');
  bundle += `// ---- ${file} ----\n` + stripModuleSyntax(source).trim() + '\n\n';
}

const names = publicApiNames();
bundle += `export {\n  ${names.join(',\n  ')}\n};\n`;

assertNoDuplicateDeclarations(bundle);

const outPath = join(outDir, 'browser.js');
writeFileSync(outPath, bundle);
console.log(`built ${outPath}`);
